defmodule SwaggerPhoenixTest.GenerateTest.Models do
  @moduledoc """
  This is the expected AST for the model provided model fixture.
  """
  def expected_ast do
    {:ok, [{:defmodule, [line: 1], [{:__aliases__, [line: 1], [:SwaggerPhoenix, :Order]}, [do: {:__block__, [], [{:use, [line: 2], [{:__aliases__, [line: 2], [:SwaggerPhoenix, :Web]}, :model]}, {:schema, [line: 4], ["orders", [do: {:__block__, [], [{:field, [line: 5], [:complete, :boolean, [default: false]]}, {:field, [line: 6], [:petId, :integer]}, {:field, [line: 7], [:quantity, :integer]}, {:field, [line: 8], [:shipDate, :string]}, {:field, [line: 9], [:status, :string]}, {:timestamps, [line: 11], []}]}]]}, {:@, [line: 14], [{:doc, [line: 14], ["Builds a changeset based on the `struct` and `params`.\n"]}]}, {:def, [line: 17], [{:changeset, [line: 17], [{:struct, [line: 17], nil}, {:\\, [line: 17], [{:params, [line: 17], nil}, {:%{}, [line: 17], []}]}]}, [do: {:|>, [line: 20], [{:|>, [line: 19], [{:struct, [line: 18], nil}, {:cast, [line: 19], [{:params, [line: 19], nil}, [:complete, :petId, :quantity, :shipDate, :status]]}]}, {:validate_required, [line: 20], [[:complete, :petId, :quantity, :shipDate, :status]]}]}]]}]}]]}, {:defmodule, [line: 1], [{:__aliases__, [line: 1], [:SwaggerPhoenix, :OrderTest]}, [do: {:__block__, [], [{:use, [line: 2], [{:__aliases__, [line: 2], [:SwaggerPhoenix, :ModelCase]}]}, {:alias, [line: 4], [{:__aliases__, [line: 4], [:SwaggerPhoenix, :Order]}]}, {:@, [line: 6], [{:valid_attrs, [line: 6], [{:%{}, [line: 6], [complete: true, petId: 42, quantity: 42, shipDate: "some content", status: "some content"]}]}]}, {:@, [line: 7], [{:invalid_attrs, [line: 7], [{:%{}, [line: 7], []}]}]}, {:test, [line: 9], ["changeset with valid attributes", [do: {:__block__, [], [{:=, [line: 10], [{:changeset, [line: 10], nil}, {{:., [line: 10], [{:__aliases__, [counter: 0, line: 10], [:Order]}, :changeset]}, [line: 10], [{:%, [line: 10], [{:__aliases__, [counter: 0, line: 10], [:Order]}, {:%{}, [line: 10], []}]}, {:@, [line: 10], [{:valid_attrs, [line: 10], nil}]}]}]}, {:assert, [line: 11], [{{:., [line: 11], [{:changeset, [line: 11], nil}, :valid?]}, [line: 11], []}]}]}]]}, {:test, [line: 14], ["changeset with invalid attributes", [do: {:__block__, [], [{:=, [line: 15], [{:changeset, [line: 15], nil}, {{:., [line: 15], [{:__aliases__, [counter: 0, line: 15], [:Order]}, :changeset]}, [line: 15], [{:%, [line: 15], [{:__aliases__, [counter: 0, line: 15], [:Order]}, {:%{}, [line: 15], []}]}, {:@, [line: 15], [{:invalid_attrs, [line: 15], nil}]}]}]}, {:refute, [line: 16], [{{:., [line: 16], [{:changeset, [line: 16], nil}, :valid?]}, [line: 16], []}]}]}]]}]}]]}]}

  end
end
